[{
  "login": "18F",
  "id": 6233994,
  "avatar_url": "https://avatars.githubusercontent.com/u/6233994?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/18F",
  "html_url": "https://github.com/18F",
  "followers_url": "https://api.github.com/users/18F/followers",
  "following_url": "https://api.github.com/users/18F/following{/other_user}",
  "gists_url": "https://api.github.com/users/18F/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/18F/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/18F/subscriptions",
  "organizations_url": "https://api.github.com/users/18F/orgs",
  "repos_url": "https://api.github.com/users/18F/repos",
  "events_url": "https://api.github.com/users/18F/events{/privacy}",
  "received_events_url": "https://api.github.com/users/18F/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "18F",
  "company": null,
  "blog": "https://18f.gsa.gov",
  "location": "United States",
  "email": "18f@gsa.gov",
  "hireable": null,
  "bio": "18F builds effective, user-centric digital services focused on the interaction between government & the people it serves. Provided by GSA.",
  "public_repos": 763,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2013-12-20T23:58:37Z",
  "updated_at": "2016-11-15T11:29:22Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4908",
    "x-ratelimit-reset": "1479951760",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0835:14456CA9:5836386E",
    "last-modified": "Tue, 15 Nov 2016 11:29:22 GMT",
    "etag": "\"0b03142b8124c776367758d970fd9d4e\"",
    "status": "200 OK"
  }
}
,{
  "login": "usnationalarchives",
  "id": 1110487,
  "avatar_url": "https://avatars.githubusercontent.com/u/1110487?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/usnationalarchives",
  "html_url": "https://github.com/usnationalarchives",
  "followers_url": "https://api.github.com/users/usnationalarchives/followers",
  "following_url": "https://api.github.com/users/usnationalarchives/following{/other_user}",
  "gists_url": "https://api.github.com/users/usnationalarchives/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/usnationalarchives/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/usnationalarchives/subscriptions",
  "organizations_url": "https://api.github.com/users/usnationalarchives/orgs",
  "repos_url": "https://api.github.com/users/usnationalarchives/repos",
  "events_url": "https://api.github.com/users/usnationalarchives/events{/privacy}",
  "received_events_url": "https://api.github.com/users/usnationalarchives/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "U.S. National Archives",
  "company": null,
  "blog": "https://www.archives.gov/developer",
  "location": "United States ",
  "email": "developer@nara.gov",
  "hireable": null,
  "bio": null,
  "public_repos": 19,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2011-10-07T15:09:36Z",
  "updated_at": "2016-10-21T17:16:08Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4813",
    "x-ratelimit-reset": "1479951760",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:082A:AD15AC3:58363969",
    "last-modified": "Fri, 21 Oct 2016 17:16:08 GMT",
    "etag": "\"6a30f81a97c594bf4d7c43f699935e6f\"",
    "status": "200 OK"
  }
}
,{
  "login": "CityOfBoston",
  "id": 4692291,
  "avatar_url": "https://avatars.githubusercontent.com/u/4692291?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/CityOfBoston",
  "html_url": "https://github.com/CityOfBoston",
  "followers_url": "https://api.github.com/users/CityOfBoston/followers",
  "following_url": "https://api.github.com/users/CityOfBoston/following{/other_user}",
  "gists_url": "https://api.github.com/users/CityOfBoston/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/CityOfBoston/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/CityOfBoston/subscriptions",
  "organizations_url": "https://api.github.com/users/CityOfBoston/orgs",
  "repos_url": "https://api.github.com/users/CityOfBoston/repos",
  "events_url": "https://api.github.com/users/CityOfBoston/events{/privacy}",
  "received_events_url": "https://api.github.com/users/CityOfBoston/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "City of Boston",
  "company": null,
  "blog": "https://www.boston.gov/departments/innovation-and-technology",
  "location": "Boston, Massachusetts, USA",
  "email": "doit@boston.gov",
  "hireable": null,
  "bio": null,
  "public_repos": 28,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2013-06-13T20:50:02Z",
  "updated_at": "2016-08-12T16:41:35Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4782",
    "x-ratelimit-reset": "1479951760",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0835:14464A11:583639B9",
    "last-modified": "Fri, 12 Aug 2016 16:41:35 GMT",
    "etag": "\"535511dfb2afacfe31986b248ad4a090\"",
    "status": "200 OK"
  }
}
,{
  "login": "presidential-innovation-fellows",
  "id": 2146920,
  "avatar_url": "https://avatars.githubusercontent.com/u/2146920?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/presidential-innovation-fellows",
  "html_url": "https://github.com/presidential-innovation-fellows",
  "followers_url": "https://api.github.com/users/presidential-innovation-fellows/followers",
  "following_url": "https://api.github.com/users/presidential-innovation-fellows/following{/other_user}",
  "gists_url": "https://api.github.com/users/presidential-innovation-fellows/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/presidential-innovation-fellows/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/presidential-innovation-fellows/subscriptions",
  "organizations_url": "https://api.github.com/users/presidential-innovation-fellows/orgs",
  "repos_url": "https://api.github.com/users/presidential-innovation-fellows/repos",
  "events_url": "https://api.github.com/users/presidential-innovation-fellows/events{/privacy}",
  "received_events_url": "https://api.github.com/users/presidential-innovation-fellows/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "Presidential Innovation Fellows",
  "company": null,
  "blog": "https://presidentialinnovationfellows.gov",
  "location": "Washington, D.C.",
  "email": "pif-team@pif.gov",
  "hireable": null,
  "bio": null,
  "public_repos": 81,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2012-08-13T20:55:59Z",
  "updated_at": "2016-11-18T10:31:36Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4778",
    "x-ratelimit-reset": "1479951760",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0833:119793E4:583639C4",
    "last-modified": "Fri, 18 Nov 2016 10:31:36 GMT",
    "etag": "\"b60ff30537b835d14033a2c36a6b16dc\"",
    "status": "200 OK"
  }
}
,{
  "login": "agrc",
  "id": 709415,
  "avatar_url": "https://avatars.githubusercontent.com/u/709415?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/agrc",
  "html_url": "https://github.com/agrc",
  "followers_url": "https://api.github.com/users/agrc/followers",
  "following_url": "https://api.github.com/users/agrc/following{/other_user}",
  "gists_url": "https://api.github.com/users/agrc/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/agrc/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/agrc/subscriptions",
  "organizations_url": "https://api.github.com/users/agrc/orgs",
  "repos_url": "https://api.github.com/users/agrc/repos",
  "events_url": "https://api.github.com/users/agrc/events{/privacy}",
  "received_events_url": "https://api.github.com/users/agrc/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "AGRC",
  "company": null,
  "blog": "http://gis.utah.gov",
  "location": "1 state office building room 5130",
  "email": "agrc@utah.gov",
  "hireable": null,
  "bio": "Automated Geographic Reference Center: Location Matters.",
  "public_repos": 90,
  "public_gists": 1,
  "followers": 0,
  "following": 0,
  "created_at": "2011-04-04T21:28:11Z",
  "updated_at": "2016-05-19T14:14:37Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4726",
    "x-ratelimit-reset": "1479951760",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0835:1446A434:58363A4F",
    "last-modified": "Thu, 19 May 2016 14:14:37 GMT",
    "etag": "\"dc43618edb088b9ff15cce913b311642\"",
    "status": "200 OK"
  }
}
,{
  "login": "GSA",
  "id": 643070,
  "avatar_url": "https://avatars.githubusercontent.com/u/643070?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/GSA",
  "html_url": "https://github.com/GSA",
  "followers_url": "https://api.github.com/users/GSA/followers",
  "following_url": "https://api.github.com/users/GSA/following{/other_user}",
  "gists_url": "https://api.github.com/users/GSA/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/GSA/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/GSA/subscriptions",
  "organizations_url": "https://api.github.com/users/GSA/orgs",
  "repos_url": "https://api.github.com/users/GSA/repos",
  "events_url": "https://api.github.com/users/GSA/events{/privacy}",
  "received_events_url": "https://api.github.com/users/GSA/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "U.S. General Services Administration",
  "company": null,
  "blog": "http://gsa.gov/developer",
  "location": "1800 F Street NW, Washington DC 20405",
  "email": "github-admins@gsa.gov",
  "hireable": null,
  "bio": "The U.S. General Services Administration",
  "public_repos": 281,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2011-02-28T17:52:47Z",
  "updated_at": "2016-10-12T20:04:22Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4466",
    "x-ratelimit-reset": "1479951760",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:082A:AD26C67:58363CF4",
    "last-modified": "Wed, 12 Oct 2016 20:04:22 GMT",
    "etag": "\"50d05a38d90f28d313405ca25005cdba\"",
    "status": "200 OK"
  }
}
,{
  "login": "nasa",
  "id": 848102,
  "avatar_url": "https://avatars.githubusercontent.com/u/848102?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/nasa",
  "html_url": "https://github.com/nasa",
  "followers_url": "https://api.github.com/users/nasa/followers",
  "following_url": "https://api.github.com/users/nasa/following{/other_user}",
  "gists_url": "https://api.github.com/users/nasa/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/nasa/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/nasa/subscriptions",
  "organizations_url": "https://api.github.com/users/nasa/orgs",
  "repos_url": "https://api.github.com/users/nasa/repos",
  "events_url": "https://api.github.com/users/nasa/events{/privacy}",
  "received_events_url": "https://api.github.com/users/nasa/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "NASA",
  "company": null,
  "blog": "http://www.nasa.gov",
  "location": "United States of America",
  "email": "github@lists.nasa.gov",
  "hireable": null,
  "bio": null,
  "public_repos": 83,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2011-06-13T22:19:22Z",
  "updated_at": "2016-10-05T15:06:17Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4387",
    "x-ratelimit-reset": "1479951760",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:082A:AD2B79D:58363DC4",
    "last-modified": "Wed, 05 Oct 2016 15:06:17 GMT",
    "etag": "\"5491a3d0ec2f2dd9a0a4e0b9fdb51e37\"",
    "status": "200 OK"
  }
}
,{
  "login": "baltimorecounty",
  "id": 4924121,
  "avatar_url": "https://avatars.githubusercontent.com/u/4924121?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/baltimorecounty",
  "html_url": "https://github.com/baltimorecounty",
  "followers_url": "https://api.github.com/users/baltimorecounty/followers",
  "following_url": "https://api.github.com/users/baltimorecounty/following{/other_user}",
  "gists_url": "https://api.github.com/users/baltimorecounty/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/baltimorecounty/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/baltimorecounty/subscriptions",
  "organizations_url": "https://api.github.com/users/baltimorecounty/orgs",
  "repos_url": "https://api.github.com/users/baltimorecounty/repos",
  "events_url": "https://api.github.com/users/baltimorecounty/events{/privacy}",
  "received_events_url": "https://api.github.com/users/baltimorecounty/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "Baltimore County",
  "company": null,
  "blog": "http://www.baltimorecountymd.gov/",
  "location": "Towson, MD, USA",
  "email": "gis@baltimorecountymd.gov",
  "hireable": null,
  "bio": null,
  "public_repos": 24,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2013-07-02T19:40:26Z",
  "updated_at": "2015-07-13T17:12:11Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4190",
    "x-ratelimit-reset": "1479951760",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0835:144A74E0:58363FC3",
    "last-modified": "Mon, 13 Jul 2015 17:12:11 GMT",
    "etag": "\"cce51a458bcc6839aa4c3d20af104dbf\"",
    "status": "200 OK"
  }
}
,{
  "login": "usnistgov",
  "id": 5330158,
  "avatar_url": "https://avatars.githubusercontent.com/u/5330158?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/usnistgov",
  "html_url": "https://github.com/usnistgov",
  "followers_url": "https://api.github.com/users/usnistgov/followers",
  "following_url": "https://api.github.com/users/usnistgov/following{/other_user}",
  "gists_url": "https://api.github.com/users/usnistgov/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/usnistgov/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/usnistgov/subscriptions",
  "organizations_url": "https://api.github.com/users/usnistgov/orgs",
  "repos_url": "https://api.github.com/users/usnistgov/repos",
  "events_url": "https://api.github.com/users/usnistgov/events{/privacy}",
  "received_events_url": "https://api.github.com/users/usnistgov/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "National Institute of Standards and Technology",
  "company": null,
  "blog": "https://www.nist.gov",
  "location": "Gaithersburg, Md. ",
  "email": "devops@nist.gov",
  "hireable": null,
  "bio": "Department of Commerce",
  "public_repos": 216,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2013-08-28T13:26:03Z",
  "updated_at": "2016-10-31T18:50:18Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4019",
    "x-ratelimit-reset": "1479951760",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0833:119C0ADC:5836417F",
    "last-modified": "Mon, 31 Oct 2016 18:50:18 GMT",
    "etag": "\"18ba9c94e5dfc38dbb6a3be08318e68e\"",
    "status": "200 OK"
  }
}
,{
  "login": "cityofsomerville",
  "id": 9576860,
  "avatar_url": "https://avatars.githubusercontent.com/u/9576860?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/cityofsomerville",
  "html_url": "https://github.com/cityofsomerville",
  "followers_url": "https://api.github.com/users/cityofsomerville/followers",
  "following_url": "https://api.github.com/users/cityofsomerville/following{/other_user}",
  "gists_url": "https://api.github.com/users/cityofsomerville/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/cityofsomerville/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/cityofsomerville/subscriptions",
  "organizations_url": "https://api.github.com/users/cityofsomerville/orgs",
  "repos_url": "https://api.github.com/users/cityofsomerville/repos",
  "events_url": "https://api.github.com/users/cityofsomerville/events{/privacy}",
  "received_events_url": "https://api.github.com/users/cityofsomerville/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "City of Somerville, MA (Official)",
  "company": null,
  "blog": "http://www.somervillema.gov",
  "location": "United States",
  "email": "dmoore@somervillema.gov",
  "hireable": null,
  "bio": "Official repositories related to data and communications from the City of Somerville, MA.",
  "public_repos": 8,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2014-11-05T19:01:40Z",
  "updated_at": "2015-04-08T00:58:56Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "3776",
    "x-ratelimit-reset": "1479951760",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:082A:AD48021:583643F8",
    "last-modified": "Wed, 08 Apr 2015 00:58:56 GMT",
    "etag": "\"74ac809521016fc20d58fcb0c4c5302d\"",
    "status": "200 OK"
  }
}
,{
  "login": "HistoryAtState",
  "id": 4379724,
  "avatar_url": "https://avatars.githubusercontent.com/u/4379724?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/HistoryAtState",
  "html_url": "https://github.com/HistoryAtState",
  "followers_url": "https://api.github.com/users/HistoryAtState/followers",
  "following_url": "https://api.github.com/users/HistoryAtState/following{/other_user}",
  "gists_url": "https://api.github.com/users/HistoryAtState/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/HistoryAtState/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/HistoryAtState/subscriptions",
  "organizations_url": "https://api.github.com/users/HistoryAtState/orgs",
  "repos_url": "https://api.github.com/users/HistoryAtState/repos",
  "events_url": "https://api.github.com/users/HistoryAtState/events{/privacy}",
  "received_events_url": "https://api.github.com/users/HistoryAtState/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "Office of the Historian, U.S. Department of State",
  "company": null,
  "blog": "https://history.state.gov/",
  "location": "Washington, D.C.",
  "email": "history@state.gov",
  "hireable": null,
  "bio": null,
  "public_repos": 21,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2013-05-08T18:06:48Z",
  "updated_at": "2016-08-17T15:45:34Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4518",
    "x-ratelimit-reset": "1479955360",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0833:11A14698:58364A73",
    "last-modified": "Wed, 17 Aug 2016 15:45:34 GMT",
    "etag": "\"77e7ef04fa148046b03d54fc8b15d06a\"",
    "status": "200 OK"
  }
}
,{
  "login": "CAGovOps",
  "id": 9556244,
  "avatar_url": "https://avatars.githubusercontent.com/u/9556244?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/CAGovOps",
  "html_url": "https://github.com/CAGovOps",
  "followers_url": "https://api.github.com/users/CAGovOps/followers",
  "following_url": "https://api.github.com/users/CAGovOps/following{/other_user}",
  "gists_url": "https://api.github.com/users/CAGovOps/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/CAGovOps/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/CAGovOps/subscriptions",
  "organizations_url": "https://api.github.com/users/CAGovOps/orgs",
  "repos_url": "https://api.github.com/users/CAGovOps/repos",
  "events_url": "https://api.github.com/users/CAGovOps/events{/privacy}",
  "received_events_url": "https://api.github.com/users/CAGovOps/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "CA Government Operations Agency",
  "company": null,
  "blog": null,
  "location": null,
  "email": "OpenCalifornia@govops.ca.gov",
  "hireable": null,
  "bio": null,
  "public_repos": 14,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2014-11-04T17:20:52Z",
  "updated_at": "2015-10-07T21:02:26Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4394",
    "x-ratelimit-reset": "1479955360",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0833:11A20D82:58364BB5",
    "last-modified": "Wed, 07 Oct 2015 21:02:26 GMT",
    "etag": "\"6c0b20e0075c225b4b69bf8bf8fb2b67\"",
    "status": "200 OK"
  }
}
,{
  "login": "CommerceGov",
  "id": 4304939,
  "avatar_url": "https://avatars.githubusercontent.com/u/4304939?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/CommerceGov",
  "html_url": "https://github.com/CommerceGov",
  "followers_url": "https://api.github.com/users/CommerceGov/followers",
  "following_url": "https://api.github.com/users/CommerceGov/following{/other_user}",
  "gists_url": "https://api.github.com/users/CommerceGov/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/CommerceGov/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/CommerceGov/subscriptions",
  "organizations_url": "https://api.github.com/users/CommerceGov/orgs",
  "repos_url": "https://api.github.com/users/CommerceGov/repos",
  "events_url": "https://api.github.com/users/CommerceGov/events{/privacy}",
  "received_events_url": "https://api.github.com/users/CommerceGov/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "The U.S. Department of Commerce",
  "company": null,
  "blog": "http://www.commerce.gov",
  "location": "Washington, DC",
  "email": "webmaster@doc.gov",
  "hireable": null,
  "bio": null,
  "public_repos": 3,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2013-04-30T17:06:34Z",
  "updated_at": "2016-08-16T05:44:03Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4391",
    "x-ratelimit-reset": "1479955360",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:082A:AD701CA:58364BBC",
    "last-modified": "Tue, 16 Aug 2016 05:44:03 GMT",
    "etag": "\"9c7080a823ddbcdc59bb2ef660257290\"",
    "status": "200 OK"
  }
}
,{
  "login": "state-hiu",
  "id": 2079497,
  "avatar_url": "https://avatars.githubusercontent.com/u/2079497?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/state-hiu",
  "html_url": "https://github.com/state-hiu",
  "followers_url": "https://api.github.com/users/state-hiu/followers",
  "following_url": "https://api.github.com/users/state-hiu/following{/other_user}",
  "gists_url": "https://api.github.com/users/state-hiu/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/state-hiu/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/state-hiu/subscriptions",
  "organizations_url": "https://api.github.com/users/state-hiu/orgs",
  "repos_url": "https://api.github.com/users/state-hiu/repos",
  "events_url": "https://api.github.com/users/state-hiu/events{/privacy}",
  "received_events_url": "https://api.github.com/users/state-hiu/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "Humanitarian Information Unit",
  "company": null,
  "blog": "https://hiu.state.gov",
  "location": "Washington, DC",
  "email": "HIU_INFO@state.gov",
  "hireable": null,
  "bio": "U.S. Department of State, Humanitarian Information Unit",
  "public_repos": 54,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2012-08-01T19:31:40Z",
  "updated_at": "2015-10-13T19:21:42Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4290",
    "x-ratelimit-reset": "1479955360",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:082A:AD74FD2:58364CC3",
    "last-modified": "Tue, 13 Oct 2015 19:21:42 GMT",
    "etag": "\"48a40f3821e6e86aa66fbc568a8e60b0\"",
    "status": "200 OK"
  }
}
,{
  "login": "usagov",
  "id": 1020090,
  "avatar_url": "https://avatars.githubusercontent.com/u/1020090?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/usagov",
  "html_url": "https://github.com/usagov",
  "followers_url": "https://api.github.com/users/usagov/followers",
  "following_url": "https://api.github.com/users/usagov/following{/other_user}",
  "gists_url": "https://api.github.com/users/usagov/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/usagov/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/usagov/subscriptions",
  "organizations_url": "https://api.github.com/users/usagov/orgs",
  "repos_url": "https://api.github.com/users/usagov/repos",
  "events_url": "https://api.github.com/users/usagov/events{/privacy}",
  "received_events_url": "https://api.github.com/users/usagov/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "USA.gov",
  "company": null,
  "blog": "http://usa.gov",
  "location": null,
  "email": "usagov-developers@gsa.gov",
  "hireable": null,
  "bio": null,
  "public_repos": 10,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2011-09-01T17:54:57Z",
  "updated_at": "2015-12-14T15:10:03Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4103",
    "x-ratelimit-reset": "1479955360",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0833:11A3B4EC:58364EAA",
    "last-modified": "Mon, 14 Dec 2015 15:10:03 GMT",
    "etag": "\"2aca4dde6aefa884c4d0490bfa5ab182\"",
    "status": "200 OK"
  }
}
,{
  "login": "USPTO",
  "id": 9042992,
  "avatar_url": "https://avatars.githubusercontent.com/u/9042992?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/USPTO",
  "html_url": "https://github.com/USPTO",
  "followers_url": "https://api.github.com/users/USPTO/followers",
  "following_url": "https://api.github.com/users/USPTO/following{/other_user}",
  "gists_url": "https://api.github.com/users/USPTO/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/USPTO/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/USPTO/subscriptions",
  "organizations_url": "https://api.github.com/users/USPTO/orgs",
  "repos_url": "https://api.github.com/users/USPTO/repos",
  "events_url": "https://api.github.com/users/USPTO/events{/privacy}",
  "received_events_url": "https://api.github.com/users/USPTO/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "U.S. Patent and Trademark Office",
  "company": null,
  "blog": "http://www.uspto.gov",
  "location": "Alexandria, Virginia",
  "email": "contactUXD@uspto.gov",
  "hireable": null,
  "bio": "Department of Commerce",
  "public_repos": 6,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2014-10-06T21:54:07Z",
  "updated_at": "2016-11-02T11:27:17Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4013",
    "x-ratelimit-reset": "1479955360",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0833:11A45517:58364F97",
    "last-modified": "Wed, 02 Nov 2016 11:27:17 GMT",
    "etag": "\"675e90aaf7aef7a12290f07388e9938d\"",
    "status": "200 OK"
  }
}
,{
  "login": "City-of-Bloomington",
  "id": 630302,
  "avatar_url": "https://avatars.githubusercontent.com/u/630302?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/City-of-Bloomington",
  "html_url": "https://github.com/City-of-Bloomington",
  "followers_url": "https://api.github.com/users/City-of-Bloomington/followers",
  "following_url": "https://api.github.com/users/City-of-Bloomington/following{/other_user}",
  "gists_url": "https://api.github.com/users/City-of-Bloomington/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/City-of-Bloomington/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/City-of-Bloomington/subscriptions",
  "organizations_url": "https://api.github.com/users/City-of-Bloomington/orgs",
  "repos_url": "https://api.github.com/users/City-of-Bloomington/repos",
  "events_url": "https://api.github.com/users/City-of-Bloomington/events{/privacy}",
  "received_events_url": "https://api.github.com/users/City-of-Bloomington/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "City of Bloomington, Indiana",
  "company": null,
  "blog": "http://bloomington.in.gov",
  "location": "Bloomington, IN",
  "email": "dev@bloomington.in.gov",
  "hireable": null,
  "bio": "Information & Technology Services department",
  "public_repos": 56,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2011-02-21T17:00:52Z",
  "updated_at": "2016-08-30T18:24:51Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4663",
    "x-ratelimit-reset": "1479958962",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0835:145A939D:5836570C",
    "last-modified": "Tue, 30 Aug 2016 18:24:51 GMT",
    "etag": "\"a9935794e762d057c923ce71f04d0f0b\"",
    "status": "200 OK"
  }
}
,{
  "login": "CISM",
  "id": 8259319,
  "avatar_url": "https://avatars.githubusercontent.com/u/8259319?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/CISM",
  "html_url": "https://github.com/CISM",
  "followers_url": "https://api.github.com/users/CISM/followers",
  "following_url": "https://api.github.com/users/CISM/following{/other_user}",
  "gists_url": "https://api.github.com/users/CISM/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/CISM/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/CISM/subscriptions",
  "organizations_url": "https://api.github.com/users/CISM/orgs",
  "repos_url": "https://api.github.com/users/CISM/repos",
  "events_url": "https://api.github.com/users/CISM/events{/privacy}",
  "received_events_url": "https://api.github.com/users/CISM/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "Community Ice Sheet Model",
  "company": null,
  "blog": "http://oceans11.lanl.gov/cism/",
  "location": null,
  "email": "cism@lanl.gov",
  "hireable": null,
  "bio": "a next-generation ice sheet model for use in predicting ice sheet evolution in a changing climate",
  "public_repos": 2,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2014-07-24T16:52:20Z",
  "updated_at": "2016-02-27T17:57:05Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4634",
    "x-ratelimit-reset": "1479958962",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0835:145AC81E:58365759",
    "last-modified": "Sat, 27 Feb 2016 17:57:05 GMT",
    "etag": "\"7347224598593f05a88d2dc02fc53d9d\"",
    "status": "200 OK"
  }
}
,{
  "login": "adlnet",
  "id": 1256328,
  "avatar_url": "https://avatars.githubusercontent.com/u/1256328?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/adlnet",
  "html_url": "https://github.com/adlnet",
  "followers_url": "https://api.github.com/users/adlnet/followers",
  "following_url": "https://api.github.com/users/adlnet/following{/other_user}",
  "gists_url": "https://api.github.com/users/adlnet/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/adlnet/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/adlnet/subscriptions",
  "organizations_url": "https://api.github.com/users/adlnet/orgs",
  "repos_url": "https://api.github.com/users/adlnet/repos",
  "events_url": "https://api.github.com/users/adlnet/events{/privacy}",
  "received_events_url": "https://api.github.com/users/adlnet/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "Advanced Distributed Learning (ADL)",
  "company": null,
  "blog": "http://www.adlnet.gov",
  "location": "Alexandria, VA and Orlando, FL",
  "email": "adlhelpdesk@adlnet.gov",
  "hireable": null,
  "bio": null,
  "public_repos": 52,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2011-12-12T01:50:29Z",
  "updated_at": "2016-10-24T12:21:19Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4628",
    "x-ratelimit-reset": "1479958962",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0835:145AD304:58365768",
    "last-modified": "Mon, 24 Oct 2016 12:21:19 GMT",
    "etag": "\"74ced68851db5ec80bd3420541f6c7de\"",
    "status": "200 OK"
  }
}
,{
  "login": "openucx",
  "id": 13118737,
  "avatar_url": "https://avatars.githubusercontent.com/u/13118737?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/openucx",
  "html_url": "https://github.com/openucx",
  "followers_url": "https://api.github.com/users/openucx/followers",
  "following_url": "https://api.github.com/users/openucx/following{/other_user}",
  "gists_url": "https://api.github.com/users/openucx/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/openucx/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/openucx/subscriptions",
  "organizations_url": "https://api.github.com/users/openucx/orgs",
  "repos_url": "https://api.github.com/users/openucx/repos",
  "events_url": "https://api.github.com/users/openucx/events{/privacy}",
  "received_events_url": "https://api.github.com/users/openucx/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "UCX",
  "company": null,
  "blog": "http://www.openucx.org",
  "location": null,
  "email": "ucx-group@elist.ornl.gov",
  "hireable": null,
  "bio": "Unified Communication X",
  "public_repos": 1,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2015-06-30T12:44:26Z",
  "updated_at": "2015-08-01T17:37:59Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4624",
    "x-ratelimit-reset": "1479958962",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:082A:ADA7C94:58365773",
    "last-modified": "Sat, 01 Aug 2015 17:37:59 GMT",
    "etag": "\"9bb91596bfae6eafdad11c651c2d528c\"",
    "status": "200 OK"
  }
}
,{
  "login": "OpenGovDC",
  "id": 7242218,
  "avatar_url": "https://avatars.githubusercontent.com/u/7242218?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/OpenGovDC",
  "html_url": "https://github.com/OpenGovDC",
  "followers_url": "https://api.github.com/users/OpenGovDC/followers",
  "following_url": "https://api.github.com/users/OpenGovDC/following{/other_user}",
  "gists_url": "https://api.github.com/users/OpenGovDC/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/OpenGovDC/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/OpenGovDC/subscriptions",
  "organizations_url": "https://api.github.com/users/OpenGovDC/orgs",
  "repos_url": "https://api.github.com/users/OpenGovDC/repos",
  "events_url": "https://api.github.com/users/OpenGovDC/events{/privacy}",
  "received_events_url": "https://api.github.com/users/OpenGovDC/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "DC Office of Open Government",
  "company": null,
  "blog": "http://www.bega-dc.gov/",
  "location": "Washington, DC",
  "email": "jada.irwin@dc.gov",
  "hireable": null,
  "bio": "DC Office of Open Government",
  "public_repos": 3,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2014-04-09T18:36:07Z",
  "updated_at": "2014-07-28T17:52:14Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4340",
    "x-ratelimit-reset": "1479958962",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0833:11AAA340:58365A55",
    "last-modified": "Mon, 28 Jul 2014 17:52:14 GMT",
    "etag": "\"e63502f4831180a4a8f04b0dbdc6a29d\"",
    "status": "200 OK"
  }
}
,{
  "login": "UV-CDAT",
  "id": 2781444,
  "avatar_url": "https://avatars.githubusercontent.com/u/2781444?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/UV-CDAT",
  "html_url": "https://github.com/UV-CDAT",
  "followers_url": "https://api.github.com/users/UV-CDAT/followers",
  "following_url": "https://api.github.com/users/UV-CDAT/following{/other_user}",
  "gists_url": "https://api.github.com/users/UV-CDAT/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/UV-CDAT/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/UV-CDAT/subscriptions",
  "organizations_url": "https://api.github.com/users/UV-CDAT/orgs",
  "repos_url": "https://api.github.com/users/UV-CDAT/repos",
  "events_url": "https://api.github.com/users/UV-CDAT/events{/privacy}",
  "received_events_url": "https://api.github.com/users/UV-CDAT/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "UV-CDAT",
  "company": null,
  "blog": "http://uv-cdat.llnl.gov",
  "location": "Earth",
  "email": "uv-cdat@llnl.gov",
  "hireable": null,
  "bio": null,
  "public_repos": 57,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2012-11-12T20:56:16Z",
  "updated_at": "2016-06-02T16:37:20Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4123",
    "x-ratelimit-reset": "1479958962",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0835:145E7571:58365C89",
    "last-modified": "Thu, 02 Jun 2016 16:37:20 GMT",
    "etag": "\"d644fdf577e88a83532c5381531bcfd4\"",
    "status": "200 OK"
  }
}
,{
  "login": "FDA",
  "id": 6471964,
  "avatar_url": "https://avatars.githubusercontent.com/u/6471964?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/FDA",
  "html_url": "https://github.com/FDA",
  "followers_url": "https://api.github.com/users/FDA/followers",
  "following_url": "https://api.github.com/users/FDA/following{/other_user}",
  "gists_url": "https://api.github.com/users/FDA/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/FDA/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/FDA/subscriptions",
  "organizations_url": "https://api.github.com/users/FDA/orgs",
  "repos_url": "https://api.github.com/users/FDA/repos",
  "events_url": "https://api.github.com/users/FDA/events{/privacy}",
  "received_events_url": "https://api.github.com/users/FDA/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "Food and Drug Administration",
  "company": null,
  "blog": "http://www.fda.gov/privacy",
  "location": "Washington, D.C.",
  "email": "open@fda.hhs.gov",
  "hireable": null,
  "bio": "The official GitHub page for the US Food and Drug Administration. Privacy Policy @ http://www.fda.gov/privacy",
  "public_repos": 5,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2014-01-22T14:20:35Z",
  "updated_at": "2016-11-19T11:01:25Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4057",
    "x-ratelimit-reset": "1479958962",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:082A:ADC3BC0:58365D38",
    "last-modified": "Sat, 19 Nov 2016 11:01:25 GMT",
    "etag": "\"c7b6908c6223c08ea9875f422d12d6cb\"",
    "status": "200 OK"
  }
}
,{
  "login": "usasearch",
  "id": 3768738,
  "avatar_url": "https://avatars.githubusercontent.com/u/3768738?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/usasearch",
  "html_url": "https://github.com/usasearch",
  "followers_url": "https://api.github.com/users/usasearch/followers",
  "following_url": "https://api.github.com/users/usasearch/following{/other_user}",
  "gists_url": "https://api.github.com/users/usasearch/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/usasearch/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/usasearch/subscriptions",
  "organizations_url": "https://api.github.com/users/usasearch/orgs",
  "repos_url": "https://api.github.com/users/usasearch/repos",
  "events_url": "https://api.github.com/users/usasearch/events{/privacy}",
  "received_events_url": "https://api.github.com/users/usasearch/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "DigitalGov Search",
  "company": null,
  "blog": "http://search.digitalgov.gov/",
  "location": "Washington, DC",
  "email": "search@support.digitalgov.gov",
  "hireable": null,
  "bio": null,
  "public_repos": 1,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2013-03-04T20:28:00Z",
  "updated_at": "2014-07-21T15:37:15Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4035",
    "x-ratelimit-reset": "1479958962",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0833:11AC4C2F:58365D71",
    "last-modified": "Mon, 21 Jul 2014 15:37:15 GMT",
    "etag": "\"cb8b57fd84f6eff4ecbb9f07d32ed361\"",
    "status": "200 OK"
  }
}
,{
  "login": "lblpbd",
  "id": 2692368,
  "avatar_url": "https://avatars.githubusercontent.com/u/2692368?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/lblpbd",
  "html_url": "https://github.com/lblpbd",
  "followers_url": "https://api.github.com/users/lblpbd/followers",
  "following_url": "https://api.github.com/users/lblpbd/following{/other_user}",
  "gists_url": "https://api.github.com/users/lblpbd/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/lblpbd/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/lblpbd/subscriptions",
  "organizations_url": "https://api.github.com/users/lblpbd/orgs",
  "repos_url": "https://api.github.com/users/lblpbd/repos",
  "events_url": "https://api.github.com/users/lblpbd/events{/privacy}",
  "received_events_url": "https://api.github.com/users/lblpbd/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "LBNL Physical Biosciences Division",
  "company": null,
  "blog": "pbd.lbl.gov",
  "location": "Berkeley, CA",
  "email": "pbdwebmaster@lbl.gov",
  "hireable": null,
  "bio": null,
  "public_repos": 10,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2012-10-31T15:41:52Z",
  "updated_at": "2016-02-27T04:19:44Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "3907",
    "x-ratelimit-reset": "1479958962",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:082A:ADCC04B:58365EC1",
    "last-modified": "Sat, 27 Feb 2016 04:19:44 GMT",
    "etag": "\"c5d6389c863d15406594b3d78579c5f7\"",
    "status": "200 OK"
  }
}
,{
  "login": "HHS",
  "id": 1470878,
  "avatar_url": "https://avatars.githubusercontent.com/u/1470878?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/HHS",
  "html_url": "https://github.com/HHS",
  "followers_url": "https://api.github.com/users/HHS/followers",
  "following_url": "https://api.github.com/users/HHS/following{/other_user}",
  "gists_url": "https://api.github.com/users/HHS/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/HHS/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/HHS/subscriptions",
  "organizations_url": "https://api.github.com/users/HHS/orgs",
  "repos_url": "https://api.github.com/users/HHS/repos",
  "events_url": "https://api.github.com/users/HHS/events{/privacy}",
  "received_events_url": "https://api.github.com/users/HHS/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "U.S. Department of Health & Human Services",
  "company": null,
  "blog": "http://www.hhs.gov/ocio/oead/index.html",
  "location": null,
  "email": "OEADHelpdesk@hhs.gov",
  "hireable": null,
  "bio": null,
  "public_repos": 20,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2012-02-24T20:26:18Z",
  "updated_at": "2016-05-02T16:16:26Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "3624",
    "x-ratelimit-reset": "1479958962",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0835:14623013:5836619F",
    "last-modified": "Mon, 02 May 2016 16:16:26 GMT",
    "etag": "\"43fa28ee5197aadfacf1378abf89d0c2\"",
    "status": "200 OK"
  }
}
,{
  "login": "USAID",
  "id": 4051799,
  "avatar_url": "https://avatars.githubusercontent.com/u/4051799?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/USAID",
  "html_url": "https://github.com/USAID",
  "followers_url": "https://api.github.com/users/USAID/followers",
  "following_url": "https://api.github.com/users/USAID/following{/other_user}",
  "gists_url": "https://api.github.com/users/USAID/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/USAID/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/USAID/subscriptions",
  "organizations_url": "https://api.github.com/users/USAID/orgs",
  "repos_url": "https://api.github.com/users/USAID/repos",
  "events_url": "https://api.github.com/users/USAID/events{/privacy}",
  "received_events_url": "https://api.github.com/users/USAID/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "United States Agency for International Development",
  "company": null,
  "blog": "http://www.usaid.gov",
  "location": "Washington, DC",
  "email": "opendata@usaid.gov",
  "hireable": null,
  "bio": "USAID is the lead U.S. Government agency that works to end extreme global poverty. Find our privacy policy at www.usaid.gov/privacy-policy",
  "public_repos": 8,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2013-04-03T18:55:49Z",
  "updated_at": "2016-07-08T18:39:20Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4897",
    "x-ratelimit-reset": "1479962564",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0835:1462F2E9:583662C0",
    "last-modified": "Fri, 08 Jul 2016 18:39:20 GMT",
    "etag": "\"0cd2bb93fa7abfb01b79ff35cf0f1d2b\"",
    "status": "200 OK"
  }
}
,{
  "login": "digital-analytics-program",
  "id": 12432573,
  "avatar_url": "https://avatars.githubusercontent.com/u/12432573?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/digital-analytics-program",
  "html_url": "https://github.com/digital-analytics-program",
  "followers_url": "https://api.github.com/users/digital-analytics-program/followers",
  "following_url": "https://api.github.com/users/digital-analytics-program/following{/other_user}",
  "gists_url": "https://api.github.com/users/digital-analytics-program/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/digital-analytics-program/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/digital-analytics-program/subscriptions",
  "organizations_url": "https://api.github.com/users/digital-analytics-program/orgs",
  "repos_url": "https://api.github.com/users/digital-analytics-program/repos",
  "events_url": "https://api.github.com/users/digital-analytics-program/events{/privacy}",
  "received_events_url": "https://api.github.com/users/digital-analytics-program/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "Digital Analytics Program",
  "company": null,
  "blog": "https://digitalgov.gov/services/dap",
  "location": "General Services Administration",
  "email": "dap@support.digitalgov.gov",
  "hireable": null,
  "bio": "The federal government's aggregated web analytics initiative.",
  "public_repos": 1,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2015-05-13T16:38:47Z",
  "updated_at": "2016-11-10T14:28:26Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4819",
    "x-ratelimit-reset": "1479962564",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:082A:ADE348A:5836638C",
    "last-modified": "Thu, 10 Nov 2016 14:28:26 GMT",
    "etag": "\"62d783043e56138d08e2896f0854a598\"",
    "status": "200 OK"
  }
}
,{
  "login": "mcc-gov",
  "id": 3706120,
  "avatar_url": "https://avatars.githubusercontent.com/u/3706120?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/mcc-gov",
  "html_url": "https://github.com/mcc-gov",
  "followers_url": "https://api.github.com/users/mcc-gov/followers",
  "following_url": "https://api.github.com/users/mcc-gov/following{/other_user}",
  "gists_url": "https://api.github.com/users/mcc-gov/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/mcc-gov/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/mcc-gov/subscriptions",
  "organizations_url": "https://api.github.com/users/mcc-gov/orgs",
  "repos_url": "https://api.github.com/users/mcc-gov/repos",
  "events_url": "https://api.github.com/users/mcc-gov/events{/privacy}",
  "received_events_url": "https://api.github.com/users/mcc-gov/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "Millennium Challenge Corporation",
  "company": null,
  "blog": "data.mcc.gov",
  "location": "Washington, DC; Global",
  "email": "opendata@mcc.gov",
  "hireable": null,
  "bio": null,
  "public_repos": 6,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2013-02-26T15:26:13Z",
  "updated_at": "2016-03-07T19:12:46Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4694",
    "x-ratelimit-reset": "1479962564",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0835:146456E4:583664D2",
    "last-modified": "Mon, 07 Mar 2016 19:12:46 GMT",
    "etag": "\"a6d17db4adf2092c5b0dc4ff63d6e10e\"",
    "status": "200 OK"
  }
}
,{
  "login": "FCC",
  "id": 632838,
  "avatar_url": "https://avatars.githubusercontent.com/u/632838?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/FCC",
  "html_url": "https://github.com/FCC",
  "followers_url": "https://api.github.com/users/FCC/followers",
  "following_url": "https://api.github.com/users/FCC/following{/other_user}",
  "gists_url": "https://api.github.com/users/FCC/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/FCC/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/FCC/subscriptions",
  "organizations_url": "https://api.github.com/users/FCC/orgs",
  "repos_url": "https://api.github.com/users/FCC/repos",
  "events_url": "https://api.github.com/users/FCC/events{/privacy}",
  "received_events_url": "https://api.github.com/users/FCC/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "The Federal Communications Commission",
  "company": null,
  "blog": "https://fcc.gov",
  "location": "Washington, D.C.",
  "email": "developer@fcc.gov",
  "hireable": null,
  "bio": null,
  "public_repos": 88,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2011-02-22T22:07:10Z",
  "updated_at": "2016-06-05T15:22:59Z",
  "meta": {
    "x-ratelimit-limit": "5000",
    "x-ratelimit-remaining": "4517",
    "x-ratelimit-reset": "1479962564",
    "x-oauth-scopes": "repo",
    "x-github-request-id": "47BF5288:0835:1465C5B4:583666A2",
    "last-modified": "Sun, 05 Jun 2016 15:22:59 GMT",
    "etag": "\"ef0cf9daad626c4c165145112be644e9\"",
    "status": "200 OK"
  }
}]
